import type { GeneratedDocument } from './docTypes';

/** Markdown export of generated document */
export function documentToMarkdown(doc: GeneratedDocument): string {
  const meta = [
    `# ${doc.title}`,
    '',
    `**Type:** ${doc.docType} · **Audience:** ${doc.audience} · **Style:** ${doc.style}`,
    `**Status:** ${doc.status} · **Version:** ${doc.version} · **Est. pages:** ${doc.estimatedPages}`,
    '',
    doc.summary ? `> ${doc.summary}\n` : '',
    doc.sources?.length ? `*Sources: ${doc.sources.join(' · ')}*\n` : '',
    '---',
    '',
  ].join('\n');

  const body = doc.sections
    .map((s) => `## ${s.title}\n\n${s.body.trim()}\n`)
    .join('\n---\n\n');

  return `${meta}${body}\n\n---\n*DMCC · Confidential · Generated by CEO Agent DocAI*\n`;
}

export function downloadMarkdown(doc: GeneratedDocument, filename?: string) {
  const md = documentToMarkdown(doc);
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = (filename || doc.title || 'document').replace(/[^\w.-]+/g, '-').slice(0, 60) + '.md';
  a.click();
  URL.revokeObjectURL(url);
}

function safeFilename(doc: GeneratedDocument, filename?: string) {
  return (filename || doc.title || 'DMCC-document').replace(/[^\w.-]+/g, '-').slice(0, 60);
}

/** Word-compatible .doc (HTML Office format — opens natively in Microsoft Word) */
export function downloadWordDocument(doc: GeneratedDocument, filename?: string) {
  const html = `<!DOCTYPE html>
<html xmlns:o="urn:schemas-microsoft-com:office:office"
      xmlns:w="urn:schemas-microsoft-com:office:word"
      xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta charset="utf-8"/>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>${escapeHtml(doc.title)}</title>
<!--[if gte mso 9]><xml>
 <w:WordDocument>
  <w:View>Print</w:View>
  <w:Zoom>100</w:Zoom>
  <w:DoNotOptimizeForBrowser/>
 </w:WordDocument>
</xml><![endif]-->
<style>
  @page WordSection1 { size: 210mm 297mm; margin: 22mm 20mm 22mm 20mm; }
  div.WordSection1 { page: WordSection1; }
  body {
    font-family: 'Montserrat', 'Calibri', 'Segoe UI', Arial, sans-serif;
    color: #1a1a2e;
    line-height: 1.55;
    font-size: 11pt;
  }
  h1 { color: #070047; font-size: 22pt; margin: 0 0 8pt; }
  h2 { color: #070047; font-size: 14pt; border-bottom: 1.5pt solid #C9A84C; padding-bottom: 4pt; margin: 18pt 0 8pt; }
  h3 { color: #070047; font-size: 12pt; margin: 12pt 0 6pt; }
  .meta { color: #555; font-size: 9pt; margin-bottom: 12pt; }
  .summary {
    background: #f4f6fb;
    border-left: 3.5pt solid #E21F7B;
    padding: 8pt 12pt;
    margin: 12pt 0 16pt;
  }
  .sec { margin-bottom: 14pt; }
  table { border-collapse: collapse; width: 100%; margin: 8pt 0; font-size: 10pt; }
  th, td { border: 1pt solid #c8d0da; padding: 5pt 7pt; text-align: left; vertical-align: top; }
  th { background: #070047; color: #fff; }
  blockquote {
    margin: 8pt 0;
    padding: 6pt 10pt;
    border-left: 2.5pt solid #C9A84C;
    color: #444;
  }
  footer {
    margin-top: 24pt;
    font-size: 8.5pt;
    color: #888;
    border-top: 1pt solid #eee;
    padding-top: 8pt;
  }
</style>
</head>
<body>
<div class="WordSection1">
  <h1>${escapeHtml(doc.title)}</h1>
  <div class="meta">${escapeHtml(doc.docType)} · ${escapeHtml(doc.audience)} · ${escapeHtml(doc.style)} · v${doc.version} · ${doc.estimatedPages} pages · ${escapeHtml(doc.status)}</div>
  ${doc.summary ? `<div class="summary">${escapeHtml(doc.summary)}</div>` : ''}
  ${doc.sections
    .map(
      (s) =>
        `<div class="sec"><h2>${escapeHtml(s.title)}</h2>${simpleMarkdownToHtml(s.body)}</div>`,
    )
    .join('')}
  <footer>DMCC · Confidential · Generated by CEO Agent DocAI</footer>
</div>
</body>
</html>`;

  const blob = new Blob(['\ufeff', html], {
    type: 'application/msword;charset=utf-8',
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${safeFilename(doc, filename)}.doc`;
  a.click();
  URL.revokeObjectURL(url);
}

/** Open print dialog for PDF / Word-via-print workflows */
export function printDocumentAsPdf(doc: GeneratedDocument) {
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/><title>${escapeHtml(
    doc.title,
  )}</title>
<style>
  @page { margin: 18mm 16mm; }
  body { font-family: 'Montserrat', 'Helvetica Neue', Arial, sans-serif; color: #1a1a2e; line-height: 1.55; max-width: 780px; margin: 0 auto; padding: 24px; }
  h1 { color: #070047; font-size: 28px; margin-bottom: 8px; }
  h2 { color: #070047; border-bottom: 2px solid #C9A84C; padding-bottom: 6px; margin-top: 32px; font-size: 18px; }
  .meta { color: #555; font-size: 12px; margin-bottom: 16px; }
  .summary { background: #f4f6fb; border-left: 4px solid #E21F7B; padding: 12px 16px; margin: 16px 0; }
  .sec { page-break-inside: avoid; margin-bottom: 20px; }
  table { border-collapse: collapse; width: 100%; margin: 12px 0; font-size: 13px; }
  th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
  th { background: #070047; color: #fff; }
  blockquote { margin: 12px 0; padding: 8px 14px; border-left: 3px solid #C9A84C; color: #444; }
  footer { margin-top: 40px; font-size: 11px; color: #888; border-top: 1px solid #eee; padding-top: 12px; }
</style></head><body>
  <h1>${escapeHtml(doc.title)}</h1>
  <div class="meta">${escapeHtml(doc.docType)} · ${escapeHtml(doc.audience)} · ${escapeHtml(doc.style)} · v${doc.version}</div>
  ${doc.summary ? `<div class="summary">${escapeHtml(doc.summary)}</div>` : ''}
  ${doc.sections
    .map(
      (s) =>
        `<div class="sec"><h2>${escapeHtml(s.title)}</h2>${simpleMarkdownToHtml(s.body)}</div>`,
    )
    .join('')}
  <footer>DMCC · Confidential · CEO Agent DocAI</footer>
  <script>window.onload=()=>{window.print();}</script>
</body></html>`;

  const w = window.open('', '_blank');
  if (!w) return;
  w.document.write(html);
  w.document.close();
}

function escapeHtml(s: string) {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Minimal markdown → HTML for print (headings, lists, tables, bold, paragraphs) */
function simpleMarkdownToHtml(md: string): string {
  const lines = md.split('\n');
  const out: string[] = [];
  let inUl = false;
  let inTable = false;

  const flushUl = () => {
    if (inUl) {
      out.push('</ul>');
      inUl = false;
    }
  };
  const flushTable = () => {
    if (inTable) {
      out.push('</tbody></table>');
      inTable = false;
    }
  };

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      flushUl();
      flushTable();
      continue;
    }
    if (/^[-*] /.test(trimmed)) {
      flushTable();
      if (!inUl) {
        out.push('<ul>');
        inUl = true;
      }
      out.push(`<li>${inline(trimmed.slice(2))}</li>`);
      continue;
    }
    if (trimmed.includes('|') && trimmed.split('|').length >= 3) {
      flushUl();
      const cells = trimmed.split('|').map((c) => c.trim()).filter(Boolean);
      if (/^[-:| ]+$/.test(trimmed)) continue;
      if (!inTable) {
        out.push('<table><thead><tr>');
        cells.forEach((c) => out.push(`<th>${inline(c)}</th>`));
        out.push('</tr></thead><tbody>');
        inTable = true;
        continue;
      }
      out.push('<tr>');
      cells.forEach((c) => out.push(`<td>${inline(c)}</td>`));
      out.push('</tr>');
      continue;
    }
    flushUl();
    flushTable();
    if (trimmed.startsWith('### ')) {
      out.push(`<h3>${inline(trimmed.slice(4))}</h3>`);
    } else if (trimmed.startsWith('## ')) {
      out.push(`<h3>${inline(trimmed.slice(3))}</h3>`);
    } else if (trimmed.startsWith('# ')) {
      out.push(`<h3>${inline(trimmed.slice(2))}</h3>`);
    } else if (trimmed.startsWith('> ')) {
      out.push(`<blockquote>${inline(trimmed.slice(2))}</blockquote>`);
    } else {
      out.push(`<p>${inline(trimmed)}</p>`);
    }
  }
  flushUl();
  flushTable();
  return out.join('\n');
}

function inline(s: string): string {
  return escapeHtml(s)
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/`(.+?)`/g, '<code>$1</code>');
}
